### ISSUE TITLE
Support for Poetry without poetry shell

### ISSUE THREAD

**Issue by renan-abm** [Textualize/trogon#11]
If I have a CLI with a script defined in a Poetry `pyproject.toml` like this

```toml
[tool.poetry.scripts]
my-cli= "my_cli.main:app"
```

and I start the TUI with `poetry run my-cli tui`, then `poetry run` won't be prepended to the command `my-cli ...` and it will fail to run. Would it be possible to support this use case?

Thanks!
