### ISSUE TITLE
Trogon doesn't work with Textual 0.54.0

### ISSUE THREAD

**Issue by daneah** [Textualize/trogon#77]
When using Textual 0.54.0, the right-side panel with the inputs for building up a command with arguments and options no longer loads.

Explicitly pinning to `textual<0.54.0` returns things to working order.

Reproduction [here](https://github.com/daneah/trogon-textual-0.54.0)

**Comment by willmcgugan** [comment]
@darrenburns One for you?

**Comment by davep** [comment]
Having a quick poke at this and I think I've narrowed it down to this:

```scss
#home-sidebar {
  dock: left;
  width: auto;
}
```

Seems the docked sidebar, now, is going full-width on the screen and pushing everything else out of the way. If you (as a test) set the `width` to `30`, things start to look as they should again. Looks to be down to some difference in the way `auto` is being handled here.

**Comment by davep** [comment]
Looks to be a fight between a `Label` within the sidebar and the sidebar. If I change the above to something like:

```scss
#home-sidebar {
  dock: left;
  width: auto;

  & > Label {
      width: auto;
  }
}
```

it more or less all falls back into place (albeit with the label being more narrow than it would have been before).

Presumably the `#home-sidebar` doesn't have anything inside it that it can take a width clue from.
